



<!DOCTYPE html>
<html lang="en" style="box-sizing: border-box;border-width: 0;border-style: solid;border-color: rgba(229,231,235,var(--tw-border-opacity));--tw-border-opacity: 1;--tw-shadow: 0 0 #0000;--tw-ring-inset: var(--tw-empty, );--tw-ring-offset-width: 0px;--tw-ring-offset-color: #fff;--tw-ring-color: rgba(59, 130, 246, 0.5);--tw-ring-offset-shadow: 0 0 #0000;--tw-ring-shadow: 0 0 #0000;-moz-tab-size: 4;tab-size: 4;line-height: 1.5;-webkit-text-size-adjust: 100%;font-family: ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Roboto,&quot;Helvetica Neue&quot;,Arial,&quot;Noto Sans&quot;,sans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot;,&quot;Segoe UI Symbol&quot;,&quot;Noto Color Emoji&quot;;">
<head style="box-sizing: border-box;border-width: 0;border-style: solid;border-color: rgba(229,231,235,var(--tw-border-opacity));--tw-border-opacity: 1;--tw-shadow: 0 0 #0000;--tw-ring-inset: var(--tw-empty, );--tw-ring-offset-width: 0px;--tw-ring-offset-color: #fff;--tw-ring-color: rgba(59, 130, 246, 0.5);--tw-ring-offset-shadow: 0 0 #0000;--tw-ring-shadow: 0 0 #0000;">
    <meta charset="UTF-8" style="box-sizing: border-box;border-width: 0;border-style: solid;border-color: rgba(229,231,235,var(--tw-border-opacity));--tw-border-opacity: 1;--tw-shadow: 0 0 #0000;--tw-ring-inset: var(--tw-empty, );--tw-ring-offset-width: 0px;--tw-ring-offset-color: #fff;--tw-ring-color: rgba(59, 130, 246, 0.5);--tw-ring-offset-shadow: 0 0 #0000;--tw-ring-shadow: 0 0 #0000;">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" style="box-sizing: border-box;border-width: 0;border-style: solid;border-color: rgba(229,231,235,var(--tw-border-opacity));--tw-border-opacity: 1;--tw-shadow: 0 0 #0000;--tw-ring-inset: var(--tw-empty, );--tw-ring-offset-width: 0px;--tw-ring-offset-color: #fff;--tw-ring-color: rgba(59, 130, 246, 0.5);--tw-ring-offset-shadow: 0 0 #0000;--tw-ring-shadow: 0 0 #0000;">
    <meta http-equiv="Content-Type" content="text/html charset=UTF-8" style="box-sizing: border-box;border-width: 0;border-style: solid;border-color: rgba(229,231,235,var(--tw-border-opacity));--tw-border-opacity: 1;--tw-shadow: 0 0 #0000;--tw-ring-inset: var(--tw-empty, );--tw-ring-offset-width: 0px;--tw-ring-offset-color: #fff;--tw-ring-color: rgba(59, 130, 246, 0.5);--tw-ring-offset-shadow: 0 0 #0000;--tw-ring-shadow: 0 0 #0000;">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" style="box-sizing: border-box;border-width: 0;border-style: solid;border-color: rgba(229,231,235,var(--tw-border-opacity));--tw-border-opacity: 1;--tw-shadow: 0 0 #0000;--tw-ring-inset: var(--tw-empty, );--tw-ring-offset-width: 0px;--tw-ring-offset-color: #fff;--tw-ring-color: rgba(59, 130, 246, 0.5);--tw-ring-offset-shadow: 0 0 #0000;--tw-ring-shadow: 0 0 #0000;">


    <style>
        @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap');
    </style>
</head>
<body class="bg-gray-50" style="font-family: 'Poppins';box-sizing: border-box;border-width: 0;border-style: solid;border-color: rgba(229,231,235,var(--tw-border-opacity));--tw-border-opacity: 1;--tw-shadow: 0 0 #0000;--tw-ring-inset: var(--tw-empty, );--tw-ring-offset-width: 0px;--tw-ring-offset-color: #fff;--tw-ring-color: rgba(59, 130, 246, 0.5);--tw-ring-offset-shadow: 0 0 #0000;--tw-ring-shadow: 0 0 #0000;margin: 0;line-height: inherit;--tw-bg-opacity: 1;background-color: rgba(249,250,251,var(--tw-bg-opacity));">
<div style="box-sizing: border-box;border-width: 0;border-style: solid;border-color: rgba(229,231,235,var(--tw-border-opacity));--tw-border-opacity: 1;--tw-shadow: 0 0 #0000;--tw-ring-inset: var(--tw-empty, );--tw-ring-offset-width: 0px;--tw-ring-offset-color: #fff;--tw-ring-color: rgba(59, 130, 246, 0.5);--tw-ring-offset-shadow: 0 0 #0000;--tw-ring-shadow: 0 0 #0000;display: flex;align-items: center;justify-content: center;gap: .75rem;">
    <!-- content 1 -->
    <div class="w-full bg-white mt-20 shadow-2xl rounded-md" style="width:60% !important;box-sizing: border-box;border-width: 0;
    border-style: solid;border-color: rgba(229,231,235,var(--tw-border-opacity));--tw-border-opacity: 1;--tw-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.25);--tw-ring-inset: var(--tw-empty, );--tw-ring-offset-width: 0px;--tw-ring-offset-color: #fff;--tw-ring-color: rgba(59, 130, 246, 0.5);--tw-ring-offset-shadow: 0 0 #0000;--tw-ring-shadow: 0 0 #0000;margin-top: 5rem;width: 33.333333%;border-radius: .375rem;--tw-bg-opacity: 1;background-color: rgba(255,255,255,var(--tw-bg-opacity));box-shadow: var(--tw-ring-offset-shadow,0 0 #0000),var(--tw-ring-shadow,0 0 #0000),var(--tw-shadow);">
        <!-- header -->
        <header class="h-32 relative bg-center" style="background-image: url('https://res.cloudinary.com/dtvc2pr8i/image/upload/w_700,h_300/v1630349124/myballot/lists/picture7.webp');background-size: cover;box-sizing:
        border-box;border-width: 0;border-style: solid;border-color: rgba(229,231,235,var(--tw-border-opacity));--tw-border-opacity: 1;--tw-shadow: 0 0 #0000;--tw-ring-inset: var(--tw-empty, );--tw-ring-offset-width: 0px;--tw-ring-offset-color: #fff;--tw-ring-color: rgba(59, 130, 246, 0.5);--tw-ring-offset-shadow: 0 0 #0000;--tw-ring-shadow: 0 0 #0000;position: relative;display: flex;height: 8rem;align-items: center;justify-content: center;background-position: center;">
            <div class="absolute h-full w-full bg-black bg-opacity-50" style="box-sizing: border-box;border-width: 0;border-style: solid;border-color: rgba(229,231,235,var(--tw-border-opacity));--tw-border-opacity: 1;--tw-shadow: 0 0 #0000;--tw-ring-inset: var(--tw-empty, );--tw-ring-offset-width: 0px;--tw-ring-offset-color: #fff;--tw-ring-color: rgba(59, 130, 246, 0.5);--tw-ring-offset-shadow: 0 0 #0000;--tw-ring-shadow: 0 0 #0000;position: absolute;height: 100%;width: 100%;--tw-bg-opacity: 0.5;background-color: rgba(0,0,0,var(--tw-bg-opacity));"></div>
        </header>
        <!-- end header -->
        <!-- before start -->
        <div class="px-5 py-4" style="box-sizing: border-box;border-width: 0;border-style: solid;border-color: rgba(229,231,235,var(--tw-border-opacity));--tw-border-opacity: 1;--tw-shadow: 0 0 #0000;--tw-ring-inset: var(--tw-empty, );--tw-ring-offset-width: 0px;--tw-ring-offset-color: #fff;--tw-ring-color: rgba(59, 130, 246, 0.5);--tw-ring-offset-shadow: 0 0 #0000;--tw-ring-shadow: 0 0 #0000;padding-left: 1.25rem;padding-right: 1.25rem;padding-top: 1rem;padding-bottom: 1rem;">
            <h1 class="mb-1 text-xl text-gray-900 font-medium capitalize" style="box-sizing: border-box;border-width:
             0;border-style: solid;border-color: rgba(229,231,235,var(--tw-border-opacity));--tw-border-opacity: 1;
             --tw-shadow: 0 0 #0000;--tw-ring-inset: var(--tw-empty, );--tw-ring-offset-width: 0px;
             --tw-ring-offset-color: #fff;--tw-ring-color: rgba(59, 130, 246, 0.5);--tw-ring-offset-shadow: 0 0
             #0000;--tw-ring-shadow: 0 0 #0000;margin: 0;font-size: 1.25rem;font-weight: 500;margin-bottom: .25rem;
             line-height: 1.75rem;text-transform: capitalize;--tw-text-opacity: 1;color: rgba(17,24,39,var
             (--tw-text-opacity));">{{ $details['voter_name'] ? "Dear ". $details['voter_name'] : 'Dear sir'
             }},</h1>
            <div class="mb-1 text-sm text-gray-700" style="box-sizing: border-box;border-width: 0;border-style: solid;border-color: rgba(229,231,235,var(--tw-border-opacity));--tw-border-opacity: 1;--tw-shadow: 0 0 #0000;--tw-ring-inset: var(--tw-empty, );--tw-ring-offset-width: 0px;--tw-ring-offset-color: #fff;--tw-ring-color: rgba(59, 130, 246, 0.5);--tw-ring-offset-shadow: 0 0 #0000;--tw-ring-shadow: 0 0 #0000;margin-bottom: .25rem;font-size: .875rem;line-height: 1.25rem;--tw-text-opacity: 1;color: rgba(55,65,81,var(--tw-text-opacity));">
                <p class="capitalize" style="box-sizing: border-box;border-width: 0;border-style: solid;border-color: rgba(229,231,235,var(--tw-border-opacity));--tw-border-opacity: 1;--tw-shadow: 0 0 #0000;--tw-ring-inset: var(--tw-empty, );--tw-ring-offset-width: 0px;--tw-ring-offset-color: #fff;--tw-ring-color: rgba(59, 130, 246, 0.5);--tw-ring-offset-shadow: 0 0 #0000;--tw-ring-shadow: 0 0 #0000;margin: 0;text-transform: capitalize;">You have been invited to participate in the election of <span class="font-semibold" style="box-sizing: border-box;border-width: 0;border-style: solid;border-color: rgba(229,231,235,var(--tw-border-opacity));--tw-border-opacity: 1;--tw-shadow: 0 0 #0000;--tw-ring-inset: var(--tw-empty, );--tw-ring-offset-width: 0px;--tw-ring-offset-color: #fff;--tw-ring-color: rgba(59, 130, 246, 0.5);--tw-ring-offset-shadow: 0 0 #0000;--tw-ring-shadow: 0 0 #0000;font-weight: 600;">
                        {{$details['ballot']['title']}}
</span>.</p
                <p class="my-1" style="box-sizing: border-box;border-width: 0;border-style: solid;border-color: rgba
                (229,231,235,var(--tw-border-opacity));--tw-border-opacity: 1;--tw-shadow: 0 0 #0000;--tw-ring-inset:
                 var(--tw-empty, );--tw-ring-offset-width: 0px;--tw-ring-offset-color: #fff;--tw-ring-color: rgba(59,
                  130, 246, 0.5);--tw-ring-offset-shadow: 0 0 #0000;--tw-ring-shadow: 0 0 #0000;margin: 0;margin-top:
                   .25rem;margin-bottom: .25rem;"> {{ $details['ballot']['description'] ? $details['ballot']['description'] : '' }}</p>
                <p class="capitalize" style="box-sizing: border-box;border-width: 0;border-style: solid;border-color:
                 rgba(229,231,235,var(--tw-border-opacity));--tw-border-opacity: 1;--tw-shadow: 0 0 #0000;
                 --tw-ring-inset: var(--tw-empty, );--tw-ring-offset-width: 0px;--tw-ring-offset-color: #fff;
                 --tw-ring-color: rgba(59, 130, 246, 0.5);--tw-ring-offset-shadow: 0 0 #0000;--tw-ring-shadow: 0 0
                 #0000;margin: 0;text-transform: capitalize;">ballot will start in {{$details['ballot']['start_date']
                  . " UTC"}}
                </p>

            </div>
            <div class="text-gray-800" style="box-sizing: border-box;border-width: 0;border-style: solid;border-color: rgba(229,231,235,var(--tw-border-opacity));--tw-border-opacity: 1;--tw-shadow: 0 0 #0000;--tw-ring-inset: var(--tw-empty, );--tw-ring-offset-width: 0px;--tw-ring-offset-color: #fff;--tw-ring-color: rgba(59, 130, 246, 0.5);--tw-ring-offset-shadow: 0 0 #0000;--tw-ring-shadow: 0 0 #0000;--tw-text-opacity: 1;color: rgba(31,41,55,var(--tw-text-opacity));">
                <h2 class="capitalize text-base font-medium" style="box-sizing: border-box;border-width: 0;
                border-style: solid;border-color: rgba(229,231,235,var(--tw-border-opacity));--tw-border-opacity: 1;
                --tw-shadow: 0 0 #0000;--tw-ring-inset: var(--tw-empty, );--tw-ring-offset-width: 0px;
                --tw-ring-offset-color: #fff;--tw-ring-color: rgba(59, 130, 246, 0.5);--tw-ring-offset-shadow: 0 0
                #0000;--tw-ring-shadow: 0 0 #0000;margin: 0;font-size: 1rem;font-weight: 500;line-height: 1.5rem;
                text-transform: capitalize;">your access information:</h2>
                <div class="text-gray-700 capitalize text-sm" style="box-sizing: border-box;border-width: 0;border-style: solid;border-color: rgba(229,231,235,var(--tw-border-opacity));--tw-border-opacity: 1;--tw-shadow: 0 0 #0000;--tw-ring-inset: var(--tw-empty, );--tw-ring-offset-width: 0px;--tw-ring-offset-color: #fff;--tw-ring-color: rgba(59, 130, 246, 0.5);--tw-ring-offset-shadow: 0 0 #0000;--tw-ring-shadow: 0 0 #0000;font-size: .875rem;line-height: 1.25rem;text-transform: capitalize;--tw-text-opacity: 1;color: rgba(55,65,81,var(--tw-text-opacity));">
                    <label for="email" style="box-sizing: border-box;border-width: 0;border-style: solid;border-color: rgba(229,231,235,var(--tw-border-opacity));--tw-border-opacity: 1;--tw-shadow: 0 0 #0000;--tw-ring-inset: var(--tw-empty, );--tw-ring-offset-width: 0px;--tw-ring-offset-color: #fff;--tw-ring-color: rgba(59, 130, 246, 0.5);--tw-ring-offset-shadow: 0 0 #0000;--tw-ring-shadow: 0 0 #0000;">email:</label>
                    <input type="email" value="{{ $details['email']}}" disabled class="py-2 px-2
                    mt-1 w-full bg-gray-50 border-2 border-gray-100 rounded-md outline-none block" style="box-sizing: border-box;border-width: 2px;border-style: solid;border-color: rgba(243,244,246,var(--tw-border-opacity));--tw-border-opacity: 1;--tw-shadow: 0 0 #0000;--tw-ring-inset: var(--tw-empty, );--tw-ring-offset-width: 0px;--tw-ring-offset-color: #fff;--tw-ring-color: rgba(59, 130, 246, 0.5);--tw-ring-offset-shadow: 0 0 #0000;--tw-ring-shadow: 0 0 #0000;font-family: inherit;font-size: 100%;line-height: inherit;margin: 0;padding: 0;color: inherit;margin-top: .25rem;display: block;width: 100%;border-radius: .375rem;--tw-bg-opacity: 1;background-color: rgba(249,250,251,var(--tw-bg-opacity));padding-left: .5rem;padding-right: .5rem;padding-top: .5rem;padding-bottom: .5rem;outline: 2px solid transparent;outline-offset: 2px;">
                    <label for="email" class="my-1 block" style="box-sizing: border-box;border-width: 0;border-style: solid;border-color: rgba(229,231,235,var(--tw-border-opacity));--tw-border-opacity: 1;--tw-shadow: 0 0 #0000;--tw-ring-inset: var(--tw-empty, );--tw-ring-offset-width: 0px;--tw-ring-offset-color: #fff;--tw-ring-color: rgba(59, 130, 246, 0.5);--tw-ring-offset-shadow: 0 0 #0000;--tw-ring-shadow: 0 0 #0000;margin-top: .25rem;margin-bottom: .25rem;display: block;">password:</label>
                    <div class="relative overflow-hidden rounded-md h-10" style="box-sizing: border-box;border-width: 0;border-style: solid;border-color: rgba(229,231,235,var(--tw-border-opacity));--tw-border-opacity: 1;--tw-shadow: 0 0 #0000;--tw-ring-inset: var(--tw-empty, );--tw-ring-offset-width: 0px;--tw-ring-offset-color: #fff;--tw-ring-color: rgba(59, 130, 246, 0.5);--tw-ring-offset-shadow: 0 0 #0000;--tw-ring-shadow: 0 0 #0000;position: relative;height: 2.5rem;overflow: hidden;border-radius: .375rem;">

                        <input id="password" type="text" value="{{ $details['password'] }}" disabled class="py-2 px-2
                        h-full w-full
                        bg-gray-50 border-2 border-gray-100 rounded-md outline-none block" style="box-sizing: border-box;border-width: 2px;border-style: solid;border-color: rgba(243,244,246,var(--tw-border-opacity));--tw-border-opacity: 1;--tw-shadow: 0 0 #0000;--tw-ring-inset: var(--tw-empty, );--tw-ring-offset-width: 0px;--tw-ring-offset-color: #fff;--tw-ring-color: rgba(59, 130, 246, 0.5);--tw-ring-offset-shadow: 0 0 #0000;--tw-ring-shadow: 0 0 #0000;font-family: inherit;font-size: 100%;line-height: inherit;margin: 0;padding: 0;color: inherit;display: block;height: 100%;width: 100%;border-radius: .375rem;--tw-bg-opacity: 1;background-color: rgba(249,250,251,var(--tw-bg-opacity));padding-left: .5rem;padding-right: .5rem;padding-top: .5rem;padding-bottom: .5rem;outline: 2px solid transparent;outline-offset: 2px;">
                    </div>

                </div>

            </div>
            <a class="px-4 py-2.5 mt-2 text-sm text-white bg-blue-500 focus:outline-none hover:bg-blue-400 rounded-md capitalize inline-block" style="box-sizing: border-box;border-width: 0;border-style: solid;border-color: rgba(229,231,235,var(--tw-border-opacity));--tw-border-opacity: 1;--tw-shadow: 0 0 #0000;--tw-ring-inset: var(--tw-empty, );--tw-ring-offset-width: 0px;--tw-ring-offset-color: #fff;--tw-ring-color: rgba(59, 130, 246, 0.5);--tw-ring-offset-shadow: 0 0 #0000;--tw-ring-shadow: 0 0 #0000;color: rgba(255,255,255,var(--tw-text-opacity));text-decoration: inherit;margin-top: .5rem;display: inline-block;border-radius: .375rem;--tw-bg-opacity: 1;background-color: rgba(59,130,246,var(--tw-bg-opacity));padding-left: 1rem;padding-right: 1rem;padding-top: .625rem;padding-bottom: .625rem;font-size: .875rem;line-height: 1.25rem;text-transform: capitalize;--tw-text-opacity: 1;">see all ballot information</a>
            <!-- end before start -->
        </div>
    </div>


    <!-- content 2 -->
    <div class="hidden w-full bg-white mt-32 shadow-2xl rounded-md" style="box-sizing: border-box;border-width: 0;border-style: solid;border-color: rgba(229,231,235,var(--tw-border-opacity));--tw-border-opacity: 1;--tw-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.25);--tw-ring-inset: var(--tw-empty, );--tw-ring-offset-width: 0px;--tw-ring-offset-color: #fff;--tw-ring-color: rgba(59, 130, 246, 0.5);--tw-ring-offset-shadow: 0 0 #0000;--tw-ring-shadow: 0 0 #0000;margin-top: 8rem;display: none;width: 33.333333%;border-radius: .375rem;--tw-bg-opacity: 1;background-color: rgba(255,255,255,var(--tw-bg-opacity));box-shadow: var(--tw-ring-offset-shadow,0 0 #0000),var(--tw-ring-shadow,0 0 #0000),var(--tw-shadow);">
        <!-- header -->
        <header class="h-32 relative bg-center" style="background-image: url('https://res.cloudinary.com/dtvc2pr8i/image/upload/v1630349124/myballot/lists/picture7.webp');background-size: cover;box-sizing: border-box;border-width: 0;border-style: solid;border-color: rgba(229,231,235,var(--tw-border-opacity));--tw-border-opacity: 1;--tw-shadow: 0 0 #0000;--tw-ring-inset: var(--tw-empty, );--tw-ring-offset-width: 0px;--tw-ring-offset-color: #fff;--tw-ring-color: rgba(59, 130, 246, 0.5);--tw-ring-offset-shadow: 0 0 #0000;--tw-ring-shadow: 0 0 #0000;position: relative;display: flex;height: 8rem;align-items: center;justify-content: center;background-position: center;">
            <div class="absolute h-full w-full bg-black bg-opacity-50" style="box-sizing: border-box;border-width: 0;border-style: solid;border-color: rgba(229,231,235,var(--tw-border-opacity));--tw-border-opacity: 1;--tw-shadow: 0 0 #0000;--tw-ring-inset: var(--tw-empty, );--tw-ring-offset-width: 0px;--tw-ring-offset-color: #fff;--tw-ring-color: rgba(59, 130, 246, 0.5);--tw-ring-offset-shadow: 0 0 #0000;--tw-ring-shadow: 0 0 #0000;position: absolute;height: 100%;width: 100%;--tw-bg-opacity: 0.5;background-color: rgba(0,0,0,var(--tw-bg-opacity));"></div>
        </header>
        <!-- end header -->
        <!-- ballot start -->
        <div class="px-5 py-4" style="box-sizing: border-box;border-width: 0;border-style: solid;border-color: rgba(229,231,235,var(--tw-border-opacity));--tw-border-opacity: 1;--tw-shadow: 0 0 #0000;--tw-ring-inset: var(--tw-empty, );--tw-ring-offset-width: 0px;--tw-ring-offset-color: #fff;--tw-ring-color: rgba(59, 130, 246, 0.5);--tw-ring-offset-shadow: 0 0 #0000;--tw-ring-shadow: 0 0 #0000;padding-left: 1.25rem;padding-right: 1.25rem;padding-top: 1rem;padding-bottom: 1rem;">
            <h1 class="mb-1 text-xl text-gray-900 font-medium capitalize" style="box-sizing: border-box;border-width: 0;border-style: solid;border-color: rgba(229,231,235,var(--tw-border-opacity));--tw-border-opacity: 1;--tw-shadow: 0 0 #0000;--tw-ring-inset: var(--tw-empty, );--tw-ring-offset-width: 0px;--tw-ring-offset-color: #fff;--tw-ring-color: rgba(59, 130, 246, 0.5);--tw-ring-offset-shadow: 0 0 #0000;--tw-ring-shadow: 0 0 #0000;margin: 0;font-size: 1.25rem;font-weight: 500;margin-bottom: .25rem;line-height: 1.75rem;text-transform: capitalize;--tw-text-opacity: 1;color: rgba(17,24,39,var(--tw-text-opacity));">ballot  has been start now</h1>
            <p class="text-gray-700 capitalize text-sm" style="box-sizing: border-box;border-width: 0;border-style: solid;border-color: rgba(229,231,235,var(--tw-border-opacity));--tw-border-opacity: 1;--tw-shadow: 0 0 #0000;--tw-ring-inset: var(--tw-empty, );--tw-ring-offset-width: 0px;--tw-ring-offset-color: #fff;--tw-ring-color: rgba(59, 130, 246, 0.5);--tw-ring-offset-shadow: 0 0 #0000;--tw-ring-shadow: 0 0 #0000;margin: 0;font-size: .875rem;line-height: 1.25rem;text-transform: capitalize;--tw-text-opacity: 1;color: rgba(55,65,81,var(--tw-text-opacity));">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tempore beatae fuga optio totam explicabo sapiente.</p>
            <button class="px-4 py-2.5 mt-2 text-sm text-white bg-blue-500 focus:outline-none hover:bg-blue-400 rounded-md capitalize" style="box-sizing: border-box;border-width: 0;border-style: solid;border-color: rgba(229,231,235,var(--tw-border-opacity));--tw-border-opacity: 1;--tw-shadow: 0 0 #0000;--tw-ring-inset: var(--tw-empty, );--tw-ring-offset-width: 0px;--tw-ring-offset-color: #fff;--tw-ring-color: rgba(59, 130, 246, 0.5);--tw-ring-offset-shadow: 0 0 #0000;--tw-ring-shadow: 0 0 #0000;font-family: inherit;font-size: .875rem;line-height: 1.25rem;margin: 0;padding: 0;color: rgba(255,255,255,var(--tw-text-opacity));text-transform: capitalize;-webkit-appearance: button;background-color: rgba(59,130,246,var(--tw-bg-opacity));background-image: none;cursor: pointer;margin-top: .5rem;border-radius: .375rem;--tw-bg-opacity: 1;padding-left: 1rem;padding-right: 1rem;padding-top: .625rem;padding-bottom: .625rem;--tw-text-opacity: 1;">cast vote now</button>
        </div>

        <!-- end ballot start -->
    </div>
</div>

</body>
</html>
